### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by oscargong** [matheuss/hyper-simple-vibrancy#1]
Does not work after added
```
    backgroundColor: 'rgba(255,0,0,0.1)',
```

and
```
  plugins: [`hyper-simple-vibrancy`],
```

**Comment by olivier-w** [comment]
This has been bugging me for days. Finally found the solution—I had to disable `Reduce Transparency` in my Accessibility settings!

<img width="670" alt="screen_shot_2016-12-14_at_6_04_43_pm" src="https://cloud.githubusercontent.com/assets/465250/21204992/f531f390-c227-11e6-92cc-028e174caba8.png">

`hyper-simple-vibrancy` now works as intended.

**Comment by matheuss** [comment]
💯
