### ISSUE TITLE
White-on-white issues

### ISSUE THREAD

**Issue by LanderN** [matheuss/hyper-simple-vibrancy#3]
This plugin causes white-on-white issues in some cases (e.g. nano in zsh).

![](http://snappyimages.nextwavesrl.netdna-cdn.com/img/c28e489b14aa36165ad8f3c8879dbd25.png)

**Comment by matheuss** [comment]
@LanderN this plugin is indented as demonstration only – I wouldn't recommend using it since I don't plan to maintain it 😅
